# Generated by Django 3.1 on 2020-11-06 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('latitude', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$', message='Not a valid latitude')])),
                ('longitude', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\s*[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$', message='Not a valid longitude')])),
                ('vehicle_number', models.CharField(max_length=15)),
                ('empty_vehicle_img', models.ImageField(upload_to='Images/Collection')),
                ('loaded_vehicle_img', models.ImageField(upload_to='Images/Collection')),
                ('lr_copy_img', models.ImageField(upload_to='Images/Collection')),
                ('vehicle_number_img', models.ImageField(upload_to='Images/Collection')),
                ('delivery_challan_img', models.ImageField(upload_to='Images/Collection')),
                ('e_way_bill_img', models.ImageField(upload_to='Images/Collection')),
                ('weighment_slip_img', models.ImageField(upload_to='Images/Collection')),
                ('weight', models.IntegerField(help_text='Weight in kG')),
                ('license_plate_no', models.CharField(blank=True, max_length=15, null=True)),
                ('manual_entry', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number_img', models.ImageField(upload_to='Images/Revisions')),
                ('revision_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(max_length=10, unique=True)),
                ('vehicle_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=500)),
                ('remark_to', models.IntegerField(choices=[(1, 'Collection Agency'), (2, 'Disposal Agency'), (4, 'Both Agency')], default=None)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True)),
                ('collection_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='company.company')),
            ],
        ),
    ]
