# Generated by Django 3.1 on 2020-11-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='disposal_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='company.company'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.order'),
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='collection_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.collectionentries'),
        ),
        migrations.AddField(
            model_name='collectionentries',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='collectionentries',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='collectionentries',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.consignment'),
        ),
    ]
