# Generated by Django 3.1 on 2020-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_weight',
            field=models.ImageField(default=10, upload_to=''),
            preserve_default=False,
        ),
    ]
