# Generated by Django 3.1 on 2020-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0005_auto_20201205_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_weight',
            field=models.CharField(max_length=10),
        ),
    ]
