# Generated by Django 3.1 on 2020-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0006_auto_20201205_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignment_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
