# Generated by Django 3.1 on 2020-12-15 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0007_auto_20201209_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentries',
            name='vehicle_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[789]\\d{9}$', message='Invalid Vehicle number')]),
        ),
    ]
