# Generated by Django 3.1 on 2020-12-15 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0008_auto_20201215_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentries',
            name='vehicle_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('(?<vnumber>[a-zA-Z][a-zA-Z]\\d\\d[a-zA-Z]{1,2}\\d\\d\\d\\d)', message='Invalid Vehicle number')]),
        ),
    ]
