# Generated by Django 3.1 on 2020-12-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0010_auto_20201216_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrevision',
            name='collection_entry',
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='consignment',
            field=models.ForeignKey(default=195, on_delete=django.db.models.deletion.CASCADE, to='transporter.consignment'),
            preserve_default=False,
        ),
    ]
