# Generated by Django 3.1 on 2020-12-21 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0012_auto_20201217_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentries',
            name='vehicle_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{1,4}$', message='Invalid vehicle number or it should be in Capital')]),
        ),
    ]
