# Generated by Django 3.1 on 2020-12-28 02:22

import digitalplatformbackend.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0014_auto_20201222_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionentries',
            name='delivery_challan_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionentries',
            name='e_way_bill_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionentries',
            name='empty_vehicle_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionentries',
            name='loaded_vehicle_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionentries',
            name='lr_copy_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionentries',
            name='vehicle_number_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionentries',
            name='weighment_slip_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Collection'),
        ),
        migrations.AlterField(
            model_name='collectionrevision',
            name='vehicle_number_img',
            field=digitalplatformbackend.custom_fields.CustomImageField(upload_to='Images/Revisions'),
        ),
    ]
