# Generated by Django 3.1 on 2021-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0015_auto_20201228_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Ongoing'), (2, 'Completed')], default=1, null=True),
        ),
    ]
