# Generated by Django 3.1 on 2020-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201208_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
