# Generated by Django 3.1 on 2020-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_allow_to_send_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
