# Generated by Django 3.1 on 2020-12-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201210_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_no',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
