# Generated by Django 3.1 on 2020-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201222_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_no',
            field=models.CharField(max_length=105, unique=True),
        ),
    ]
