# Generated by Django 3.1 on 2020-11-06 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloading_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('latitude', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)$', message='Not a valid latitude')])),
                ('longitude', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\s*[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$', message='Not a valid longitude')])),
                ('loaded_vehicle_img', models.ImageField(upload_to='Images/Disposals')),
                ('vehicle_number_img', models.ImageField(upload_to='Images/Disposals')),
                ('weighment_slip_img', models.ImageField(upload_to='Images/Disposals')),
                ('weight', models.IntegerField(help_text='Weight in kG')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3)),
            ],
        ),
    ]
