# Generated by Django 3.1 on 2020-11-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('user', '0001_initial'),
        ('transporter', '0001_initial'),
        ('disposal_agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalentries',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='disposalentries',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='disposalentries',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporter.consignment'),
        ),
    ]
