# Generated by Django 3.1 on 2020-11-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal_agency', '0002_auto_20201106_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposalentries',
            old_name='status',
            new_name='disposal_status',
        ),
    ]
