# Generated by Django 3.1 on 2020-12-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposal_agency', '0003_auto_20201118_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalentries',
            name='license_plate_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='disposalentries',
            name='manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DisposalRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_vehicle_number_img', models.ImageField(upload_to='Images/Revisions')),
                ('revision_date', models.DateTimeField(auto_now_add=True)),
                ('disposal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disposal_agency.disposalentries')),
            ],
        ),
    ]
